CREATE TABLE Customer(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(300) NOT NULL
);

CREATE TABLE Student(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(100) NOT NULL,
    contact VARCHAR(15) NOT NULL,
    picture MEDIUMBLOB NOT NULL
);